### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Nicklas185105** [UnRealModding/JAVD#21]
When on a server, the dimension keeps resetting each time you enter thje world.
I also checked it on a singleplayer with LAN turned on, then the world also resets.

The modpack I'm playing is FTB Endeavour.

**Comment by Bass2style** [comment]
i have same issue on my custom pack, both JAVD and JAMD are affected.

the mod was working without issue before, but i think it's related to a Forge change.
i actually use Forge 36.0.58 (FTB seems also using this version), and my previously version used was 36.0.43.

not tested a downgrade yet, because i need to do a full server backup etc, but i also have that issue.

edit : Forge 36.0.46 seems also affected, some mods required this version in their update, so i tested this build, 
i'm testing builds 43 (that was working before), 44 and 45 now.

edit 2 : falling back to Forge 36.0.43 is working. some mods in my pack needs 0.46 to work, but JAVD is working on this version.
trying .44 and .45 to see wich one breaks things.

edit 3 : build 36.0.44 seems also working, now testing build 45.

edit 4 tested Build 36.0.45, and JAVD is working on this build, so, there is a problem that affects Forge 36.0.46 and up.

edit 5 : not tested versions between (because 0.58 is also buggy), but 36.1.0 seems working, so, something between this build, and Release Build seems fixing JAVD.

edit 6 (final one i think, because i'm bored. xD) : i've tested a .58 fallback, and changes made in 36.1.0 where rollbacked, and new changes in the dimension seems persistent when teleporting back in the overwold.
this bug is really strange.

**Comment by UnRealDinnerbone** [comment]
Can this issue happen with just JAMD installed?

**Comment by Bass2style** [comment]
i should try to build a server only with JAVD/JAMD, but i'm not testing further today, sorry. :/

**Comment by Bass2style** [comment]
when playing around with RFTDim, i found out that i can't "dial" rftools dimensions, with some chunk saving errors in the console when i hit "dial", after a bit of research, i found out that bug on AE2's Tracker, i need to try that out, but i think that javd/javm bug is coming from AE2's bug. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5069

someone in the comments are talking about Endeavour 1.1, like the OP of this report. 

i should check in the console when joining/leaving the void or mining dimension if this happens also in our case. 

a commit seems commited to fix the bug above, but not released in a public build, OP of the AE2 Report says that downgrading AE2 to Alpha 1 seems to fix their issues, so i should try this to see if your mods are still affected, but i need to allocate time to do it.

**Comment by Nicklas185105** [comment]
There is an update for Endeavour where AE2 is getting downgraded, so I will try to update

**Comment by Nicklas185105** [comment]
Downgrading AE2 to Alpha 1 solved the issue with the Void World

**Comment by Bass2style** [comment]
ok, so finding out that post on Applied's GIT helped us. so, it's well coming from AE2's bug.

**Comment by UnRealDinnerbone** [comment]
thanks for checking that out, closing this since it a AE2 bug
