### ISSUE TITLE
Config option for normal day/night Cycle

### ISSUE THREAD

**Issue by Saereth** [UnRealModding/JAVD#24]
Would it be possible to get a config option to allow for a normal day/night cycle? Currently using the 1.16.x version. Thank you

**Comment by UnRealDinnerbone** [comment]
With a datapack change fixed_time from 6000 to false data/javd/dimension_type/void.json

**Comment by TilBlechschmidt** [comment]
In case anybody else finds this issue in the future I'd like to add my findings:

Setting the `fixed_time` property of the dimension type to `false` will result in `false` being coerced to `0` and thus the time in the void dimension gets fixed to early morning. In order to restore the normal "overworld" day/night cycle, the property has to be set to `null`.

I've attached an example datapack in case anybody wants a day/night cycle but can't be bothered to figure out how datapacks work.

[javd-daynightcycle.zip](https://github.com/UnRealDinnerbone/JAVD/files/6717298/javd-daynightcycle.zip)
